# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21bf357ce83f755ab4d49beb7c9a9b1c79e5f6aa13264cedc679283c9073f10faaf51e47567f6f1dc044952fccaf491b5a2ff334bcd6c843ce938bf6f6056434

test:
  secret_key_base: 50e5e68b099f08aceeea5a68299f24168e5d754b27810d172a8ffd7f58705d24aaa936f0f7b5078ea2312cd24f218884b4e4ec0c9843b94e45f4edc07a94b781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
